/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NsfwPredictor */

#ifndef _Included_NsfwPredictor
#define _Included_NsfwPredictor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NsfwPredictor
 * Method:    predict
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_NsfwPredictor_predict
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
